/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.gameProject11;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.lang.*;
import java.util.*;
/**
 *
 * @author ADOHome
 */
public class JFrame extends javax.swing.JFrame {

    private CardLayout makeCard;
    private CardLayout makePicCard;
    private CardLayout makeCardMsg;
    private int gameChoice;
    private int uTotalScore ;
    private int compTotalScore;
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        makeCard = new CardLayout();
        jPanelMain.setLayout(makeCard);
        jPanelMain.add("jPanel1", jPanelInitial);
        jPanelMain.add("jPanel2", jPanelGame);
        jPanelMain.add("jPanel3", jPanelDirections);
        jPanelMain.add("jPanel4", jPanelEnd);
        
        makePicCard = new CardLayout();
        center.setLayout(makePicCard);
        center.add("jPanelPic1", jPanelPic1);
        center.add("jPanelPic2", jPanelPic2);
        center.add("jPanelPic3", jPanelPic3);
        center.add("jPanelPic4", jPanelPic4);
        center.add("jPanelPic5", jPanelPic5);
        center.add("jPanelPic6", jPanelPic6);
        center.add("jPanelPic7", jPanelPic7);
        center.add("jPanelPic8", jPanelPic8);
        center.add("jPanelPic9", jPanelPic9);
        center.add("jPanelPic10", jPanelPic10);
        
        makeCardMsg = new CardLayout();
        jPanelMsg.setLayout(makeCardMsg);
        jPanelMsg.add("jPanelWin", jPanelWin);
        jPanelMsg.add("jPanelLose", jPanelLose);
    }
    public void goPan1(){
        makeCard.show(jPanelMain, "jPanel1");  // jPaneInitial, opening panel
    }
    public void goPan2(){
        makeCard.show(jPanelMain, "jPanel2");  //jPanelGame, game screen
    }
    public void goPan3(){
        makeCard.show(jPanelMain, "jPanel3");  //jPanelDirections, directions from initial screen how to play button
    }
    public void goPan4(){
        makeCard.show(jPanelMain, "jPanel4");  //jPanelEnd, last screen that prints winner and loser
    }
    
    
    public void goPanPic1(){
        makePicCard.show(center, "jPanelPic1");  // jPanePic1 = blank pic
    }
    public void goPanPic2(){
        makePicCard.show(center, "jPanelPic2");  // jPanePic1 = blank pic
    }
    public void goPanPic3(){
        makePicCard.show(center, "jPanelPic3");  // jPanePic1 = blank pic
    }
    public void goPanPic4(){
        makePicCard.show(center, "jPanelPic4");  // jPanePic1 = blank pic
    }
    public void goPanPic5(){
        makePicCard.show(center, "jPanelPic5");  // jPanePic1 = blank pic
    }
    public void goPanPic6(){
        makePicCard.show(center, "jPanelPic6");  // jPanePic1 = blank pic
    }
    public void goPanPic7(){
        makePicCard.show(center, "jPanelPic7");  // jPanePic1 = blank pic
    }
    public void goPanPic8(){
        makePicCard.show(center, "jPanelPic8");  // jPanePic1 = blank pic
    }
    public void goPanPic9(){
        makePicCard.show(center, "jPanelPic9");  // jPanePic1 = blank pic
    }
    public void goPanPic10(){
        makePicCard.show(center, "jPanelPic10");  // jPanePic1 = blank pic
    }
    
    
    
    public void goPanWin(){
        makeCardMsg.show(jPanelMsg, "jPanelWin");  // jPaneInitial, opening panel
    }
    public void goPanLose(){
        makeCardMsg.show(jPanelMsg, "jPanelLose");  //jPanelGame, game screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMain = new javax.swing.JPanel();
        jPanelDirections = new javax.swing.JPanel();
        jLabelDirections = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        dirContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelDescritptions = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanelEnd = new javax.swing.JPanel();
        GameOver = new javax.swing.JLabel();
        winnerMessage = new javax.swing.JLabel();
        playAgain = new javax.swing.JButton();
        jPanelMsg = new javax.swing.JPanel();
        jPanelWin = new javax.swing.JPanel();
        winPic = new javax.swing.JLabel();
        jPanelLose = new javax.swing.JPanel();
        losePic = new javax.swing.JLabel();
        jPanelInitial = new javax.swing.JPanel();
        toGame = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        toGame3 = new javax.swing.JButton();
        toGame5 = new javax.swing.JButton();
        Directions = new javax.swing.JButton();
        spacer1 = new javax.swing.JPanel();
        spacer2 = new javax.swing.JPanel();
        jPanelGame = new javax.swing.JPanel();
        topCenter = new javax.swing.JPanel();
        jLabelTop = new javax.swing.JLabel();
        jLabelTop2 = new javax.swing.JLabel();
        gameType = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        spacerLeft = new javax.swing.JPanel();
        winWord = new javax.swing.JLabel();
        compPlay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spacer7 = new javax.swing.JPanel();
        spacer9 = new javax.swing.JPanel();
        spacer10 = new javax.swing.JPanel();
        spacer11 = new javax.swing.JPanel();
        spacer15 = new javax.swing.JPanel();
        scores = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        uScore = new javax.swing.JLabel();
        uScoreNum = new javax.swing.JLabel();
        compScoreNum = new javax.swing.JLabel();
        compScore = new javax.swing.JLabel();
        center = new javax.swing.JPanel();
        jPanelPic1 = new javax.swing.JPanel();
        picture1 = new javax.swing.JLabel();
        jPanelPic2 = new javax.swing.JPanel();
        picture2 = new javax.swing.JLabel();
        jPanelPic3 = new javax.swing.JPanel();
        picture3 = new javax.swing.JLabel();
        jPanelPic4 = new javax.swing.JPanel();
        picture4 = new javax.swing.JLabel();
        jPanelPic5 = new javax.swing.JPanel();
        picture5 = new javax.swing.JLabel();
        jPanelPic6 = new javax.swing.JPanel();
        picture6 = new javax.swing.JLabel();
        jPanelPic7 = new javax.swing.JPanel();
        picture7 = new javax.swing.JLabel();
        jPanelPic8 = new javax.swing.JPanel();
        picture8 = new javax.swing.JLabel();
        jPanelPic9 = new javax.swing.JPanel();
        picture9 = new javax.swing.JLabel();
        jPanelPic10 = new javax.swing.JPanel();
        picture10 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        rock = new javax.swing.JButton();
        scissors = new javax.swing.JButton();
        paper = new javax.swing.JButton();
        spacer3 = new javax.swing.JPanel();
        bottomRight = new javax.swing.JPanel();
        toInitial = new javax.swing.JButton();
        spacer5 = new javax.swing.JPanel();
        spacerRIght = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelMain.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelMain.setSize(new java.awt.Dimension(800, 600));
        jPanelMain.setLayout(new java.awt.CardLayout());

        jPanelDirections.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDirections.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelDirections.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelDirections.setLayout(new java.awt.GridBagLayout());

        jLabelDirections.setFont(new java.awt.Font("Noteworthy", 0, 48)); // NOI18N
        jLabelDirections.setText("How to Play");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelDirections.add(jLabelDirections, gridBagConstraints);

        Back.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHome(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 50);
        jPanelDirections.add(Back, gridBagConstraints);

        dirContainer.setBackground(new java.awt.Color(204, 204, 204));
        dirContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dirContainer.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelDescritptions.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        jLabelDescritptions.setText("Choose the type of game that you want to play");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabelDescritptions, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tamil MN", 0, 20)); // NOI18N
        jLabel3.setText("Best of 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 25, 1, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tamil MN", 0, 20)); // NOI18N
        jLabel2.setText("Single Game");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 25, 1, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tamil MN", 0, 18)); // NOI18N
        jLabel10.setText("Play one game against the Computer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 50, 1, 20);
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tamil MN", 0, 18)); // NOI18N
        jLabel11.setText("Play until either the User or the Computer wins 2 games");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jPanel1.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tamil MN", 0, 18)); // NOI18N
        jLabel12.setText("Play until either the User or the Computer wins 3 games");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 50, 1, 20);
        jPanel1.add(jLabel12, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tamil MN", 0, 20)); // NOI18N
        jLabel4.setText("Best of 5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 25, 1, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel5.setSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        dirContainer.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        jLabel5.setText("Play your turn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tamil MN", 0, 20)); // NOI18N
        jLabel6.setText("Paper");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 25, 1, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tamil MN", 0, 18)); // NOI18N
        jLabel13.setText("Click on one of the buttons to choose your move");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 5);
        jPanel2.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tamil MN", 0, 20)); // NOI18N
        jLabel14.setText("Rock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 25, 1, 0);
        jPanel2.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tamil MN", 0, 20)); // NOI18N
        jLabel15.setText("Scissors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 25, 1, 0);
        jPanel2.add(jLabel15, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel6.setSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        dirContainer.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        jLabel7.setText("Keep Track of Your Score");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tamil MN", 0, 18)); // NOI18N
        jLabel8.setText("The score is shown on the left side of the screen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 2, 0);
        jPanel3.add(jLabel8, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel10.setSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jPanel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        dirContainer.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Tamil MN", 0, 24)); // NOI18N
        jLabel9.setText("Play Again");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel4.add(jLabel9, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tamil MN", 0, 18)); // NOI18N
        jLabel16.setText("Click the button to play again or close the window to exit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 2, 0);
        jPanel4.add(jLabel16, gridBagConstraints);

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel11.setSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        dirContainer.add(jPanel4, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel7.setSize(new java.awt.Dimension(0, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        dirContainer.add(jPanel7, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel8.setSize(new java.awt.Dimension(0, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        dirContainer.add(jPanel8, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel9.setSize(new java.awt.Dimension(0, 10));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        dirContainer.add(jPanel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelDirections.add(dirContainer, gridBagConstraints);

        jPanelMain.add(jPanelDirections, "card2");

        jPanelEnd.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEnd.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelEnd.setLayout(new java.awt.GridBagLayout());

        GameOver.setFont(new java.awt.Font("Noteworthy", 0, 72)); // NOI18N
        GameOver.setText("Game Over");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanelEnd.add(GameOver, gridBagConstraints);

        winnerMessage.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        winnerMessage.setText("Winner Message");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanelEnd.add(winnerMessage, gridBagConstraints);

        playAgain.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        playAgain.setText("Play Again");
        playAgain.setMargin(new java.awt.Insets(2, 4, 2, 4));
        playAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgain(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 70, 70);
        jPanelEnd.add(playAgain, gridBagConstraints);

        jPanelMsg.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMsg.setLayout(new java.awt.CardLayout());

        jPanelWin.setBackground(new java.awt.Color(255, 255, 255));

        winPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/winner_pic5.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelWinLayout = new javax.swing.GroupLayout(jPanelWin);
        jPanelWin.setLayout(jPanelWinLayout);
        jPanelWinLayout.setHorizontalGroup(
            jPanelWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
            .addGroup(jPanelWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelWinLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(winPic)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelWinLayout.setVerticalGroup(
            jPanelWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(jPanelWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelWinLayout.createSequentialGroup()
                    .addComponent(winPic)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelMsg.add(jPanelWin, "card2");

        jPanelLose.setBackground(new java.awt.Color(255, 255, 255));

        losePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/loser_pic1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelLoseLayout = new javax.swing.GroupLayout(jPanelLose);
        jPanelLose.setLayout(jPanelLoseLayout);
        jPanelLoseLayout.setHorizontalGroup(
            jPanelLoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
            .addGroup(jPanelLoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLoseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(losePic)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelLoseLayout.setVerticalGroup(
            jPanelLoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(jPanelLoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLoseLayout.createSequentialGroup()
                    .addComponent(losePic)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelMsg.add(jPanelLose, "card3");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelEnd.add(jPanelMsg, gridBagConstraints);

        jPanelMain.add(jPanelEnd, "card5");

        jPanelInitial.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInitial.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelInitial.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelInitial.setLayout(new java.awt.GridBagLayout());

        toGame.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        toGame.setText("Single Game");
        toGame.setMargin(new java.awt.Insets(2, 4, 2, 4));
        toGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToGame(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanelInitial.add(toGame, gridBagConstraints);

        Title.setFont(new java.awt.Font("Noteworthy", 0, 48)); // NOI18N
        Title.setText("Rock, Paper, Scissors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        jPanelInitial.add(Title, gridBagConstraints);

        toGame3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        toGame3.setText("Best of 3");
        toGame3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        toGame3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGame3(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelInitial.add(toGame3, gridBagConstraints);

        toGame5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        toGame5.setText("Best of 5");
        toGame5.setMargin(new java.awt.Insets(2, 4, 2, 4));
        toGame5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGame5(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelInitial.add(toGame5, gridBagConstraints);

        Directions.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Directions.setText("How to Play");
        Directions.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Directions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToDirections(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 70, 0, 70);
        jPanelInitial.add(Directions, gridBagConstraints);

        spacer1.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout spacer1Layout = new javax.swing.GroupLayout(spacer1);
        spacer1.setLayout(spacer1Layout);
        spacer1Layout.setHorizontalGroup(
            spacer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer1Layout.setVerticalGroup(
            spacer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanelInitial.add(spacer1, gridBagConstraints);

        spacer2.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout spacer2Layout = new javax.swing.GroupLayout(spacer2);
        spacer2.setLayout(spacer2Layout);
        spacer2Layout.setHorizontalGroup(
            spacer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer2Layout.setVerticalGroup(
            spacer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanelInitial.add(spacer2, gridBagConstraints);

        jPanelMain.add(jPanelInitial, "card3");

        jPanelGame.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGame.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelGame.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelGame.setLayout(new java.awt.GridBagLayout());

        topCenter.setBackground(new java.awt.Color(255, 255, 255));
        topCenter.setLayout(new java.awt.GridBagLayout());

        jLabelTop.setFont(new java.awt.Font("Noteworthy", 0, 48)); // NOI18N
        jLabelTop.setText("Rock, Paper, Scissors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        topCenter.add(jLabelTop, gridBagConstraints);

        jLabelTop2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelTop2.setText("User vs Computer");
        jLabelTop2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 2, 0);
        topCenter.add(jLabelTop2, gridBagConstraints);

        gameType.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        gameType.setText("Game Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 17, 0);
        topCenter.add(gameType, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        jPanelGame.add(topCenter, gridBagConstraints);

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setLayout(new java.awt.GridBagLayout());

        spacerLeft.setBackground(new java.awt.Color(204, 204, 255));
        spacerLeft.setPreferredSize(new java.awt.Dimension(1, 0));
        spacerLeft.setSize(new java.awt.Dimension(1, 0));

        javax.swing.GroupLayout spacerLeftLayout = new javax.swing.GroupLayout(spacerLeft);
        spacerLeft.setLayout(spacerLeftLayout);
        spacerLeftLayout.setHorizontalGroup(
            spacerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacerLeftLayout.setVerticalGroup(
            spacerLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        left.add(spacerLeft, gridBagConstraints);

        winWord.setBackground(new java.awt.Color(255, 255, 255));
        winWord.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        winWord.setText("Win");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        left.add(winWord, gridBagConstraints);

        compPlay.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        compPlay.setForeground(new java.awt.Color(255, 153, 51));
        compPlay.setText("Play");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        left.add(compPlay, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Computer Plays:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        left.add(jLabel1, gridBagConstraints);

        spacer7.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout spacer7Layout = new javax.swing.GroupLayout(spacer7);
        spacer7.setLayout(spacer7Layout);
        spacer7Layout.setHorizontalGroup(
            spacer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer7Layout.setVerticalGroup(
            spacer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        left.add(spacer7, gridBagConstraints);

        spacer9.setBackground(new java.awt.Color(255, 255, 255));
        spacer9.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout spacer9Layout = new javax.swing.GroupLayout(spacer9);
        spacer9.setLayout(spacer9Layout);
        spacer9Layout.setHorizontalGroup(
            spacer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer9Layout.setVerticalGroup(
            spacer9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        left.add(spacer9, gridBagConstraints);

        spacer10.setBackground(new java.awt.Color(255, 255, 255));
        spacer10.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout spacer10Layout = new javax.swing.GroupLayout(spacer10);
        spacer10.setLayout(spacer10Layout);
        spacer10Layout.setHorizontalGroup(
            spacer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer10Layout.setVerticalGroup(
            spacer10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        left.add(spacer10, gridBagConstraints);

        spacer11.setBackground(new java.awt.Color(255, 255, 255));
        spacer11.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout spacer11Layout = new javax.swing.GroupLayout(spacer11);
        spacer11.setLayout(spacer11Layout);
        spacer11Layout.setHorizontalGroup(
            spacer11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer11Layout.setVerticalGroup(
            spacer11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        left.add(spacer11, gridBagConstraints);

        spacer15.setBackground(new java.awt.Color(255, 255, 255));
        spacer15.setPreferredSize(new java.awt.Dimension(1, 0));

        javax.swing.GroupLayout spacer15Layout = new javax.swing.GroupLayout(spacer15);
        spacer15.setLayout(spacer15Layout);
        spacer15Layout.setHorizontalGroup(
            spacer15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer15Layout.setVerticalGroup(
            spacer15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        left.add(spacer15, gridBagConstraints);

        scores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scores.setLayout(new java.awt.GridBagLayout());

        scoreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        scoreLabel.setText("Score");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        scores.add(scoreLabel, gridBagConstraints);

        uScore.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        uScore.setText("User's Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        scores.add(uScore, gridBagConstraints);

        uScoreNum.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        uScoreNum.setForeground(new java.awt.Color(51, 51, 255));
        uScoreNum.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 7);
        scores.add(uScoreNum, gridBagConstraints);

        compScoreNum.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        compScoreNum.setForeground(new java.awt.Color(255, 153, 51));
        compScoreNum.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(7, 17, 7, 7);
        scores.add(compScoreNum, gridBagConstraints);

        compScore.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        compScore.setText("Computer's Score:");
        compScore.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        scores.add(compScore, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        left.add(scores, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelGame.add(left, gridBagConstraints);

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setLayout(new java.awt.CardLayout());

        jPanelPic1.setBackground(new java.awt.Color(255, 255, 255));

        picture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/RPCcyclesized2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic1Layout = new javax.swing.GroupLayout(jPanelPic1);
        jPanelPic1.setLayout(jPanelPic1Layout);
        jPanelPic1Layout.setHorizontalGroup(
            jPanelPic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic1Layout.setVerticalGroup(
            jPanelPic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic1, "card2");

        jPanelPic2.setBackground(new java.awt.Color(255, 255, 255));

        picture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uRock_cRock.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic2Layout = new javax.swing.GroupLayout(jPanelPic2);
        jPanelPic2.setLayout(jPanelPic2Layout);
        jPanelPic2Layout.setHorizontalGroup(
            jPanelPic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic2Layout.setVerticalGroup(
            jPanelPic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic2, "card3");

        jPanelPic3.setBackground(new java.awt.Color(255, 255, 255));

        picture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uPaper_cPaper.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic3Layout = new javax.swing.GroupLayout(jPanelPic3);
        jPanelPic3.setLayout(jPanelPic3Layout);
        jPanelPic3Layout.setHorizontalGroup(
            jPanelPic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic3Layout.setVerticalGroup(
            jPanelPic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic3, "card4");

        jPanelPic4.setBackground(new java.awt.Color(255, 255, 255));

        picture4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uScissors_cScissors.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic4Layout = new javax.swing.GroupLayout(jPanelPic4);
        jPanelPic4.setLayout(jPanelPic4Layout);
        jPanelPic4Layout.setHorizontalGroup(
            jPanelPic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic4Layout.setVerticalGroup(
            jPanelPic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic4, "card5");

        jPanelPic5.setBackground(new java.awt.Color(255, 255, 255));

        picture5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uPaper_cRock.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic5Layout = new javax.swing.GroupLayout(jPanelPic5);
        jPanelPic5.setLayout(jPanelPic5Layout);
        jPanelPic5Layout.setHorizontalGroup(
            jPanelPic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic5Layout.setVerticalGroup(
            jPanelPic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic5, "card6");

        jPanelPic6.setBackground(new java.awt.Color(255, 255, 255));

        picture6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uScissors_cPaper.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic6Layout = new javax.swing.GroupLayout(jPanelPic6);
        jPanelPic6.setLayout(jPanelPic6Layout);
        jPanelPic6Layout.setHorizontalGroup(
            jPanelPic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic6Layout.setVerticalGroup(
            jPanelPic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic6, "card7");

        jPanelPic7.setBackground(new java.awt.Color(255, 255, 255));

        picture7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uRock_cScissors.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic7Layout = new javax.swing.GroupLayout(jPanelPic7);
        jPanelPic7.setLayout(jPanelPic7Layout);
        jPanelPic7Layout.setHorizontalGroup(
            jPanelPic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic7Layout.setVerticalGroup(
            jPanelPic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic7, "card8");

        jPanelPic8.setBackground(new java.awt.Color(255, 255, 255));

        picture8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uScissors_cRock.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic8Layout = new javax.swing.GroupLayout(jPanelPic8);
        jPanelPic8.setLayout(jPanelPic8Layout);
        jPanelPic8Layout.setHorizontalGroup(
            jPanelPic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic8Layout.setVerticalGroup(
            jPanelPic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic8, "card9");

        jPanelPic9.setBackground(new java.awt.Color(255, 255, 255));

        picture9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uRock_cPaper.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic9Layout = new javax.swing.GroupLayout(jPanelPic9);
        jPanelPic9.setLayout(jPanelPic9Layout);
        jPanelPic9Layout.setHorizontalGroup(
            jPanelPic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic9Layout.setVerticalGroup(
            jPanelPic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic9, "card10");

        jPanelPic10.setBackground(new java.awt.Color(255, 255, 255));

        picture10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gameProject11/uPaper_cScissors.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPic10Layout = new javax.swing.GroupLayout(jPanelPic10);
        jPanelPic10.setLayout(jPanelPic10Layout);
        jPanelPic10Layout.setHorizontalGroup(
            jPanelPic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPic10Layout.setVerticalGroup(
            jPanelPic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelPic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPic10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(picture10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        center.add(jPanelPic10, "card11");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelGame.add(center, gridBagConstraints);

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setLayout(new java.awt.GridBagLayout());

        rock.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        rock.setText("Rock");
        rock.setMargin(new java.awt.Insets(2, 4, 2, 4));
        rock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 10, 10);
        right.add(rock, gridBagConstraints);

        scissors.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        scissors.setText("Scissors");
        scissors.setMargin(new java.awt.Insets(2, 4, 2, 4));
        scissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorsClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 40, 10);
        right.add(scissors, gridBagConstraints);

        paper.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        paper.setText("Paper");
        paper.setMargin(new java.awt.Insets(2, 4, 2, 4));
        paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        right.add(paper, gridBagConstraints);

        spacer3.setBackground(new java.awt.Color(255, 255, 255));
        spacer3.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout spacer3Layout = new javax.swing.GroupLayout(spacer3);
        spacer3.setLayout(spacer3Layout);
        spacer3Layout.setHorizontalGroup(
            spacer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer3Layout.setVerticalGroup(
            spacer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        right.add(spacer3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanelGame.add(right, gridBagConstraints);

        bottomRight.setBackground(new java.awt.Color(255, 255, 255));
        bottomRight.setLayout(new java.awt.GridBagLayout());

        toInitial.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        toInitial.setText("Start Over");
        toInitial.setMargin(new java.awt.Insets(2, 4, 2, 4));
        toInitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHome(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 10);
        bottomRight.add(toInitial, gridBagConstraints);

        spacer5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout spacer5Layout = new javax.swing.GroupLayout(spacer5);
        spacer5.setLayout(spacer5Layout);
        spacer5Layout.setHorizontalGroup(
            spacer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacer5Layout.setVerticalGroup(
            spacer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        bottomRight.add(spacer5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanelGame.add(bottomRight, gridBagConstraints);

        spacerRIght.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout spacerRIghtLayout = new javax.swing.GroupLayout(spacerRIght);
        spacerRIght.setLayout(spacerRIghtLayout);
        spacerRIghtLayout.setHorizontalGroup(
            spacerRIghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spacerRIghtLayout.setVerticalGroup(
            spacerRIghtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 2.0;
        jPanelGame.add(spacerRIght, gridBagConstraints);

        jPanelMain.add(jPanelGame, "card4");

        getContentPane().add(jPanelMain, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToGame
        //^this button is on initial screen "Single Game"^
        
        gameChoice = 1; //this button signals a single game
        uTotalScore = 0;//keep this for 1st game, 1st time you call pan2()
        compTotalScore = 0;//keep this for 1st game, 1st time you call pan2()
        gameType.setText("Single Game");
        compPlay.setText("");
        winWord.setText("");
        goPan2();
    }//GEN-LAST:event_goToGame

    private void backToHome(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHome
        //^this button is on Directions screen "DONE"^
        goPan1();
    }//GEN-LAST:event_backToHome

    private void toHome(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toHome
        //^this button is on Game screen "Start Over"^
        //every time we go to Initial Panel we reset global variables
        gameChoice = 0;
        uTotalScore = 0;
        compTotalScore = 0;
        uScoreNum.setText(" " + uTotalScore);
        compScoreNum.setText(" " + compTotalScore);
        winnerMessage.setText("");
        compPlay.setText("");
        winWord.setText("");
        goPanPic1();
        goPan1();
    }//GEN-LAST:event_toHome

    private void rockClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockClicked
        //^this button is on game screen "Rock"^
        gameCalc(1);
    }//GEN-LAST:event_rockClicked

    private void scissorsClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorsClicked
        //^this button is on game screen "Scissors"^
        gameCalc(3);
    }//GEN-LAST:event_scissorsClicked

    private void paperClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperClicked
        //^this button is on game screen "Paper"^
        gameCalc(2);
        
    }//GEN-LAST:event_paperClicked

    private void goToDirections(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToDirections
        goPan3();
    }//GEN-LAST:event_goToDirections

    private void toGame3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGame3
        //^this button is on initial screen "Best of 3"^
        
        gameChoice = 2; //best 2 out of 3
        uTotalScore = 0;//keep this for 1st game, 1st time you call pan2()
        compTotalScore = 0;//keep this for 1st game, 1st time you call pan2()
        gameType.setText("Best of 3");
        compPlay.setText("");
        winWord.setText("");
        goPan2();
        
    }//GEN-LAST:event_toGame3

    private void toGame5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGame5
        //^this button is on initial screen "Best of 5"^
        
        gameChoice = 3; //best 3 out of 5
        uTotalScore = 0; //keep this for 1st game, 1st time you call pan2()
        compTotalScore = 0;//keep this for 1st game, 1st time you call pan2()
        gameType.setText("Best of 5");
        compPlay.setText("");
        winWord.setText("");
        goPan2();
        
    }//GEN-LAST:event_toGame5

    private void playAgain(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgain
        //^this button is on end screen after you win or lose game^
        //every time we go to Initial Panel we reset global variables
        
        gameChoice = 0;
        uTotalScore = 0;
        compTotalScore = 0;
        uScoreNum.setText(" " + uTotalScore);
        compScoreNum.setText(" " + compTotalScore);
        winnerMessage.setText("");
        compPlay.setText("");
        winWord.setText("");
        goPanPic1();
        goPan1();
    }//GEN-LAST:event_playAgain

    private void gameCalc(int user){
        //Calculate winner
         //0 = tie, 1 = user win, 2 = computer win
        int comp = compChoice();
        if (comp == 1){
            compPlay.setText("ROCK");
        }else if (comp == 2){
            compPlay.setText("PAPER");
        }else if (comp == 3){
            compPlay.setText("SCISSORS");
        }
        
        //1 = rock, 2 = paper, 3 = scissors
        if ( (comp == 1)&&(user == 1) ){//tie
            goPanPic2();
            winnerCalc(0);
        }else if ( (comp == 2)&&(user == 2) ){//tie
            goPanPic3();
            winnerCalc(0);
        }else if ( (comp == 3)&&(user == 3) ){//tie
            goPanPic4();
            winnerCalc(0);
        }else if ( (comp == 1)&&(user == 2) ){//user win
            goPanPic5();
            winnerCalc(1);
        }else if ( (comp == 2)&&(user == 3) ){//user win
            goPanPic6();
            winnerCalc(1);
        }else if ( (comp == 3)&&(user == 1) ){//user win
            goPanPic7();
            winnerCalc(1);
        }else if ( (comp == 1)&&(user == 3) ){//coputer win
            goPanPic8();
            winnerCalc(2);
        }else if ( (comp == 2)&&(user == 1) ){//computer win
            goPanPic9();
            winnerCalc(2);
        }else if ( (comp == 3)&&(user == 2) ){//computer win
            goPanPic10();
            winnerCalc(2);
        }
    }
    private void winnerCalc(int winnerNum){
        if (winnerNum ==0){  //tie
            winWord.setText("TIE");
            uScoreNum.setText(" " + uTotalScore);
            compScoreNum.setText(" " + compTotalScore);
        }
        
        else if (winnerNum == 1){ //User has won
            winWord.setText("YOU WIN");
            uTotalScore++; //increment winner total score
            uScoreNum.setText(" " + uTotalScore);
            compScoreNum.setText(" " + compTotalScore);
            
            if (uTotalScore == gameChoice){
                winnerMessage.setText("Congradulations, You Have Won!");
                goPanWin();
                goPan4(); // go to winner screen
            }
            
        }
        
        else if (winnerNum == 2){ //computer has won
            winWord.setText("YOU LOSE");
            compTotalScore++; //increment computer total score
            uScoreNum.setText(" " + uTotalScore);
            compScoreNum.setText(" " + compTotalScore);
            
            if (compTotalScore == gameChoice){
                winnerMessage.setText("So Sorry, You Lost");
                goPanLose();
                goPan4(); // go to winner screen
            }
            
        }
    }
    private int compChoice(){
        int random = 0;
        random = getRandomNumberInRange(1, 3);
        
        return random;
    }
    private static int getRandomNumberInRange(int min, int max) {

		if (min >= max) {
			throw new IllegalArgumentException("max must be greater than min");
		}

		Random r = new Random();
		return r.nextInt((max - min) + 1) + min;
	}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Directions;
    private javax.swing.JLabel GameOver;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bottomRight;
    private javax.swing.JPanel center;
    private javax.swing.JLabel compPlay;
    private javax.swing.JLabel compScore;
    private javax.swing.JLabel compScoreNum;
    private javax.swing.JPanel dirContainer;
    private javax.swing.JLabel gameType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDescritptions;
    private javax.swing.JLabel jLabelDirections;
    private javax.swing.JLabel jLabelTop;
    private javax.swing.JLabel jLabelTop2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDirections;
    private javax.swing.JPanel jPanelEnd;
    private javax.swing.JPanel jPanelGame;
    private javax.swing.JPanel jPanelInitial;
    private javax.swing.JPanel jPanelLose;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMsg;
    private javax.swing.JPanel jPanelPic1;
    private javax.swing.JPanel jPanelPic10;
    private javax.swing.JPanel jPanelPic2;
    private javax.swing.JPanel jPanelPic3;
    private javax.swing.JPanel jPanelPic4;
    private javax.swing.JPanel jPanelPic5;
    private javax.swing.JPanel jPanelPic6;
    private javax.swing.JPanel jPanelPic7;
    private javax.swing.JPanel jPanelPic8;
    private javax.swing.JPanel jPanelPic9;
    private javax.swing.JPanel jPanelWin;
    private javax.swing.JPanel left;
    private javax.swing.JLabel losePic;
    private javax.swing.JButton paper;
    private javax.swing.JLabel picture1;
    private javax.swing.JLabel picture10;
    private javax.swing.JLabel picture2;
    private javax.swing.JLabel picture3;
    private javax.swing.JLabel picture4;
    private javax.swing.JLabel picture5;
    private javax.swing.JLabel picture6;
    private javax.swing.JLabel picture7;
    private javax.swing.JLabel picture8;
    private javax.swing.JLabel picture9;
    private javax.swing.JButton playAgain;
    private javax.swing.JPanel right;
    private javax.swing.JButton rock;
    private javax.swing.JButton scissors;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JPanel scores;
    private javax.swing.JPanel spacer1;
    private javax.swing.JPanel spacer10;
    private javax.swing.JPanel spacer11;
    private javax.swing.JPanel spacer15;
    private javax.swing.JPanel spacer2;
    private javax.swing.JPanel spacer3;
    private javax.swing.JPanel spacer5;
    private javax.swing.JPanel spacer7;
    private javax.swing.JPanel spacer9;
    private javax.swing.JPanel spacerLeft;
    private javax.swing.JPanel spacerRIght;
    private javax.swing.JButton toGame;
    private javax.swing.JButton toGame3;
    private javax.swing.JButton toGame5;
    private javax.swing.JButton toInitial;
    private javax.swing.JPanel topCenter;
    private javax.swing.JLabel uScore;
    private javax.swing.JLabel uScoreNum;
    private javax.swing.JLabel winPic;
    private javax.swing.JLabel winWord;
    private javax.swing.JLabel winnerMessage;
    // End of variables declaration//GEN-END:variables
}
